[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "music_clap"
version = "0.1.0"
description = "CLI wrapper around LAION-CLAP to produce audio embeddings"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
music-clap = "music_clap.__main__:main"
