#!/usr/bin/env zsh
# se: simple extractor for common archive formats
# Usage:
#   se [here] FILE
#   Extracts FILE based on extension. If 'here' is specified, extracts into
#   the current directory (behavior may vary per format). Without 'here',
#   attempts to extract into a subdirectory named after FILE.
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  sed -n '2,6p' "$0" | sed 's/^# \{0,1\}//'; exit 0
fi

main() {
    if [[ -f $1 ]]; then
        case $1 in
            *.rar) unar "$1" ;;
            *.tar.bz2) tar -x --use-compress-program=lbzip2 -f "$1" ;;
            *.tar.gz) tar -x --use-compress-program=rapidgzip -f "$1" ;;
            *.tar) tar xvf "$1" ;;
            *.tar.zstd) tar xf "$1";;
            *.tbz2) tar -x --use-compress-program=lbzip2 -f "$1" ;;
            *.tgz) tar -x --use-compress-program=rapidgzip -f "$1" ;;
            *.txz) XZ_DEFAULTS="-T 0" tar xf "$1" ;; # XZ_DEFAULTS="-T 0" is enough
            *.tzstd) tar xf "$1";;
            *.zip) punzip "$1" ;;
            *.Z) uncompress "$1" ;;

            *.7z) 7z x "$1" ;;
            *.bz2) lbunzip2 "$1" ;;
            *.gz) rapidgzip -d -P 0 "$1" ;;
            *.xz) XZ_DEFAULTS="-T 0" unxz "$1" ;; # XZ_DEFAULTS="-T 0" is enough
        esac
    fi
}

main_here() {
    if [[ -f $1 ]]; then
        case $1 in
            *.rar) unar -o "${1%%.rar}" "$1" ;;
            *.tar.bz2) tar -x --use-compress-program=lbzip2 -f "$1" ;;
            *.tar.gz) tar -x --use-compress-program=rapidgzip -f "$1" ;;
            *.tar) tar -C "${1%%.tar}" xf "$1" ;;
            *.tar.zstd) tar -C "${1%%.tar.zstd}" xf "$1";;
            *.tbz2) tar -C "${1%%.tbz2}" -x --use-compress-program=lbzip2 -f "$1" ;;
            *.tgz) tar -C "${1%%.tgz}" -x --use-compress-program=rapidgzip -f "$1" ;;
            *.txz) XZ_DEFAULTS="-T 0" tar -C "${1%%.txz}" xf "$1" ;; # XZ_DEFAULTS="-T 0" is enough
            *.tar.xz) XZ_DEFAULTS="-T 0" tar -C "${1%%.tar.xz}" xf "$1" ;; # XZ_DEFAULTS="-T 0" is enough
            *.tzstd) tar -C "${1%%.tzstd}" xf "$1";;
            *.tzst) tar -C "${1%%.tzst}" xf "$1";;
            *.zip) punzip -d "${1%%.zip}" "$1" ;;
            *.Z) uncompress "$1" ;;

            *.7z) 7z x "$1" ;;
            *.bz2) lbunzip2 "$1" ;;
            *.gz) rapidgzip -d -P 0 "$1" ;;
            *.xz) XZ_DEFAULTS="-T 0" unxz "$1" ;; # XZ_DEFAULTS="-T 0" is enough
        esac
    fi
}

if [[ $1 == "here" ]]; then
    shift
    main_here "$@"
else
    main "$@"
fi
