# Minimal cargo-deny config. Tweak as needed per-project.
[advisories]
vulnerability = "deny"
unmaintained = "warn"
unsound = "deny"
yanked = "warn"
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "deny"
deny = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"

