zstyle :plugin:fast-syntax-highlighting theme "neg"
typeset -g FAST_THEME_NAME="neg"
: ${FAST_HIGHLIGHT_STYLES[negdefault]:=none}
: ${FAST_HIGHLIGHT_STYLES[negunknown-token]:=none}
: ${FAST_HIGHLIGHT_STYLES[negreserved-word]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[negalias]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[negsuffix-alias]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[negbuiltin]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[negfunction]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[negcommand]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[negprecommand]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[negcommandseparator]:=none}
: ${FAST_HIGHLIGHT_STYLES[neghashed-command]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[negpath]:=}
: ${FAST_HIGHLIGHT_STYLES[negpath_pathseparator]:=}
: ${FAST_HIGHLIGHT_STYLES[negglobbing]:=fg=114}
: ${FAST_HIGHLIGHT_STYLES[negglobbing-ext]:=fg=244}
: ${FAST_HIGHLIGHT_STYLES[neghistory-expansion]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[negsingle-hyphen-option]:=fg=177}
: ${FAST_HIGHLIGHT_STYLES[negdouble-hyphen-option]:=fg=177}
: ${FAST_HIGHLIGHT_STYLES[negback-quoted-argument]:=none}
: ${FAST_HIGHLIGHT_STYLES[negsingle-quoted-argument]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[negdouble-quoted-argument]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[negdollar-quoted-argument]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[negback-or-dollar-double-quoted-argument]:=fg=177}
: ${FAST_HIGHLIGHT_STYLES[negback-dollar-quoted-argument]:=fg=177}
: ${FAST_HIGHLIGHT_STYLES[negassign]:=none}
: ${FAST_HIGHLIGHT_STYLES[negredirection]:=fg=blue}
: ${FAST_HIGHLIGHT_STYLES[negcomment]:=fg=black,bold}
: ${FAST_HIGHLIGHT_STYLES[negvariable]:=none}
: ${FAST_HIGHLIGHT_STYLES[negmathvar]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[negmathnum]:=fg=154}
: ${FAST_HIGHLIGHT_STYLES[negmatherr]:=fg=red}
: ${FAST_HIGHLIGHT_STYLES[negassign-array-bracket]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[negfor-loop-variable]:=none}
: ${FAST_HIGHLIGHT_STYLES[negfor-loop-number]:=fg=154}
: ${FAST_HIGHLIGHT_STYLES[negfor-loop-operator]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[negfor-loop-separator]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[negexec-descriptor]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[neghere-string-tri]:=fg=141}
: ${FAST_HIGHLIGHT_STYLES[neghere-string-text]:=bg=19}
: ${FAST_HIGHLIGHT_STYLES[neghere-string-var]:=fg=177,bg=19}
: ${FAST_HIGHLIGHT_STYLES[negsecondary]:=zdharma}
: ${FAST_HIGHLIGHT_STYLES[negcase-input]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[negcase-parentheses]:=fg=141}
: ${FAST_HIGHLIGHT_STYLES[negcase-condition]:=bg=19}
: ${FAST_HIGHLIGHT_STYLES[negcorrect-subtle]:=bg=55}
: ${FAST_HIGHLIGHT_STYLES[negincorrect-subtle]:=bg=52}
: ${FAST_HIGHLIGHT_STYLES[negsubtle-separator]:=none}
: ${FAST_HIGHLIGHT_STYLES[negsubtle-bg]:=bg=17}
: ${FAST_HIGHLIGHT_STYLES[negpath-to-dir]:=fg=154,underline}
: ${FAST_HIGHLIGHT_STYLES[negpaired-bracket]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[negbracket-level-1]:=fg=117}
: ${FAST_HIGHLIGHT_STYLES[negbracket-level-2]:=fg=141}
: ${FAST_HIGHLIGHT_STYLES[negbracket-level-3]:=fg=90}
: ${FAST_HIGHLIGHT_STYLES[negglobal-alias]:=bg=19}
: ${FAST_HIGHLIGHT_STYLES[negsubcommand]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[negsingle-sq-bracket]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[negdouble-sq-bracket]:=fg=63}
: ${FAST_HIGHLIGHT_STYLES[negdouble-paren]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[negoptarg-string]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[negoptarg-number]:=fg=154}
: ${FAST_HIGHLIGHT_STYLES[negrecursive-base]:=fg=186}
