### Generated by compress_theme.py — do not hand-edit
typeset -g FAST_THEME_NAME=neg

typeset -gA FAST_HIGHLIGHT_STYLES=(
  [negdefault]='none'
  [negunknown-token]='none'
  [negreserved-word]='fg=146'
  [negalias]='fg=63'
  [negsuffix-alias]='fg=63'
  [negbuiltin]='fg=63'
  [negfunction]='fg=63'
  [negcommand]='fg=63'
  [negprecommand]='fg=63'
  [negcommandseparator]='none'
  [neghashed-command]='fg=63'
  [negpath]='none'
  [negpath_pathseparator]='fg=4'
  [negglobbing]='fg=114'
  [negglobbing-ext]='fg=244'
  [neghistory-expansion]='fg=blue,bold'
  [negsingle-hyphen-option]='fg=177'
  [negdouble-hyphen-option]='fg=177'
  [negback-quoted-argument]='none'
  [negsingle-quoted-argument]='fg=146'
  [negdouble-quoted-argument]='fg=146'
  [negdollar-quoted-argument]='fg=146'
  [negback-or-dollar-double-quoted-argument]='fg=177'
  [negback-dollar-quoted-argument]='fg=177'
  [negassign]='none'
  [negredirection]='fg=blue'
  [negcomment]='fg=black,bold'
  [negvariable]='none'
  [negmathvar]='fg=blue,bold'
  [negmathnum]='fg=154'
  [negmatherr]='fg=red'
  [negassign-array-bracket]='fg=63'
  [negfor-loop-variable]='none'
  [negfor-loop-number]='fg=154'
  [negfor-loop-operator]='fg=146'
  [negfor-loop-separator]='fg=109'
  [negexec-descriptor]='fg=yellow,bold'
  [neghere-string-tri]='fg=141'
  [neghere-string-text]='bg=19'
  [neghere-string-var]='fg=177,bg=19'
  [negsecondary]='zdharma'
  [negcase-input]='fg=63'
  [negcase-parentheses]='fg=141'
  [negcase-condition]='bg=19'
  [negcorrect-subtle]='bg=55'
  [negincorrect-subtle]='bg=52'
  [negsubtle-separator]='none'
  [negsubtle-bg]='bg=17'
  [negpath-to-dir]='fg=248,underline'
  [negpaired-bracket]='bg=blue'
  [negbracket-level-1]='fg=117'
  [negbracket-level-2]='fg=141'
  [negbracket-level-3]='fg=90'
  [negglobal-alias]='bg=19'
  [negsubcommand]='fg=146'
  [negsingle-sq-bracket]='fg=63'
  [negdouble-sq-bracket]='fg=63'
  [negdouble-paren]='fg=146'
  [negoptarg-string]='fg=146'
  [negoptarg-number]='fg=154'
  [negrecursive-base]='fg=186'
)

_setstyle(){ local k=$1 v=$2; [[ -n ${FAST_HIGHLIGHT_STYLES[$k]-} ]] || FAST_HIGHLIGHT_STYLES[$k]=$v; }

for ext in aria2 bib cap dhall dmp dtd dump epf fxml htm html jhtm json5 jsonc jsonl jsonnet libsonnet mht msg ndjson nix pcap pgn plist rdata rnc rng rss sgml stackdump tf tfstate tfvars tmtheme toml xml xsd yaml yml zcompdump; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=29'; done
for ext in scpt swift; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=219,italic'; done
for ext in bck h hh hpp hxx ii s sassc swo temp tmp; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=247'; done
for ext in msql mysql pgsql prql sql; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=83'; done
for ext in info latex norg org tex textile; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=249,italic'; done
for ext in ahk gemspec ipynb netrc ovpn xsh; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=33,italic'; done
for ext in asm cljc cljs cljw el elc eln nim nimble sx v vala vapi zig; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=64'; done
for ext in btm db fmp12 fp7 ldf localstorage mdb mde nc sqlite typelib; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=99'; done
for ext in ai drw eps eps2 eps3 epsf epsi ps svg svgz; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=25'; done
for ext in attheme colors rasi s3m sid sty sug tdesktop tdy tfm tfnt theme ttytterrc urlview webloc; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=5,bold'; done
for ext in am hin in m4 old out scan skip; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=235'; done
for ext in err error mdump stderr; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=160,bold,underline'; done
for ext in adoc asciidoc etx markdown md mdx mkd pod rst wiki; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=246'; done
for ext in aux bbl blg cache class incomplete mfasl part pyc zx; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=244,bold'; done
for ext in 3ga aiff amr au caf dat dts fcm mod spl wv wvc; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=5'; done
for ext in arc arj bdf gsf klwp pcf pfa pfb rar tar warc; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=61'; done
for ext in c cc cp cpp cxx; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=24,bold,italic'; done
for ext in f f03 f08 f90 f95 for ftn java jnlp; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=245,italic'; done
for ext in cdr dicom flif indd m nth pbm pgm ppm tga xpm; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=110'; done
for ext in alac ape flac wav; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=34,bold,italic'; done
for ext in csv ifo r tsv; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=28'; done
for ext in aac axa m4a m4b m4r mka mp2 mp3 mp4a mpc oga ogg opus ra spx wma; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=37,italic'; done
for ext in 7z ace afm alp alz br bz bz2 cpio dfont dz fnt fon gz lha lrz lz lz4 lzh lzma lzo otf pfm rz s7z t7z taz tbz tbz2 tgz tlz ttf txz tz tzo woff woff2 xz z zip zipx zoo zpaq zst zstd zz; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=61,bold'; done
for ext in kak vim viminfo vimp; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=56'; done
for ext in a dll so; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=22,bold'; done
_setstyle "${FAST_THEME_NAME}file-extensions-e" 'fg=245,bold'
for ext in cfg conf hgrc htoprc ini json msmtprc vil; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=2'; done
for ext in avi divx flc fli gl m2ts m2v m4v mjpeg mkv mov mp4 mp4v mpeg mpg nuv ogm qt rm rmvb sample vob; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=75,bold'; done
for ext in ear jar sar target war; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=73'; done
for ext in apk bfe bsp cab cl deb egg enc ffp gem gpg jad lisp lua md5 ml moon msi p12 p7s pak par pem pgp pk3 pkg pub rkt rpm scm sfv sha1 sig signature st5 udeb vdf vpk; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=74'; done
for ext in o rlib; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=236,bold'; done
for ext in dmg img ipa iso mdf nrg sparseimage toast vcd vfd; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=134,bold'; done
_setstyle "${FAST_THEME_NAME}file-extensions-t" 'fg=28,bold'
for ext in cr cs service vb vba vbs; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=81'; done
for ext in epub fb2 lit mobi; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=15'; done
for ext in bat cmd css less odp pps ppt ppts pptx sass scss snippets; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=31'; done
for ext in added cfusertextencoding ds_store ex example feature ics localized tg vcard vcf zwc; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=244'; done
for ext in bak swp; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=247,bold'; done
for ext in allow device dl jpeg jpg mng pcx; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=24'; done
for ext in astro ejs mustache pug svelte vue; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=250,bold'; done
_setstyle "${FAST_THEME_NAME}file-extensions-dylib" 'fg=241'
for ext in archimate car nib; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=57'; done
for ext in lesshst map nfo; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=248,bold'; done
for ext in pas rs; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=73,italic'; done
for ext in doc docm docx dot dotm entitlements odb odm odt pages pbxproj xcconfig xcsettings xcuserstate xcworkspacedata; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=1'; done
for ext in 32x a00 a52 a64 a78 adf atr cdi fm2 gb gba gbc gel gg ggl ipk j64 nds nes sav sms st; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=222'; done
for ext in agda agdai hi hs lagda; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=34'; done
for ext in cbr cbz chm pdf; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=15,bold'; done
for ext in com exe net ru timer xbm; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=111'; done
for ext in icls jidgo mk modulemap n3 nt owl qml rake rdf sbt torrent ttl; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=60'; done
for ext in fehbg fonts git gitattributes github; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=36'; done
for ext in bin djv djvu icc icm; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=249'; done
for ext in bash bash_history csh dash fish ksh sh tcsh zsh; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=103,bold'; done
for ext in pptsm pptxm; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=31,underline'; done
for ext in bmp tcc; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=110,bold'; done
for ext in gif icns ico; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=25,bold'; done
for ext in cda pcm; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=34,bold'; done
for ext in bpg cgm cr2 emf jxl png psd pxd pxm webp xcf xwd yuv; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=24,bold'; done
for ext in lhs tcl tk; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=34,italic'; done
for ext in 3g2 3gp asf f4v flv gp3 gp4 ogv webm; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=75,italic'; done
for ext in snapshot wgsl; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=97'; done
for ext in bash_login bash_logout bash_profile profile sed zlogin zlogout zprofile zshenv; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=103,italic'; done
for ext in 82p 83p 8eu 8xe 8xp; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=204'; done
for ext in erl glsl go sc scala; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=70,italic'; done
for ext in cjs coffee dart gs js jsx mjs ts tsx; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=74,italic'; done
for ext in comp frag vert; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=142'; done
for ext in cue m3u m3u8 pls xspf; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=28,italic'; done
for ext in deny fvd qcow qcow2 vdi vhd vhdx vmdk; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=89'; done
for ext in gnumeric numbers ods xla xls xlsm; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=14'; done
for ext in containerignore dockerignore gitignore; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=240'; done
for ext in diff patch; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'bg=7,fg=16,bold'; done
for ext in pacnew prisma reg; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=33,underline'; done
for ext in asc key; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=74,bold'; done
for ext in dff dsf; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=36,bold,italic'; done
for ext in accdb accde accdr accdt; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=161'; done
for ext in ctp pc php pm xmodmap; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=4'; done
for ext in pid state; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=1,bold'; done
for ext in anx axv ogx; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=13,bold'; done
for ext in xlsx xltm xltx; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=14,underline'; done
for ext in muttrc tif tiff; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=33'; done
for ext in erb irb xresources; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=33,bold'; done
for ext in mid midi; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=37,underline'; done
for ext in hgignore psf rc sls xkb; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=2,italic'; done
_setstyle "${FAST_THEME_NAME}file-extensions-mf" 'fg=110,italic'
for ext in clj fnl; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=64,italic'; done
for ext in dwg ply stl wrl; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=216'; done
_setstyle "${FAST_THEME_NAME}file-extensions-pl" 'fg=73,bold'
for ext in eml http; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=90,bold'; done
_setstyle "${FAST_THEME_NAME}file-extensions-py" 'fg=30,bold'
for ext in desktop socket wmv; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=75'; done
for ext in xauthority xinitrc; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=4,bold'; done
_setstyle "${FAST_THEME_NAME}file-extensions-lnk" 'fg=39'
_setstyle "${FAST_THEME_NAME}file-extensions-rb" 'fg=33,bold,italic'
_setstyle "${FAST_THEME_NAME}file-extensions-log" 'fg=238,bold'
_setstyle "${FAST_THEME_NAME}file-extensions-rom" 'fg=222,bold'
for ext in crx xpi; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=74,underline'; done
_setstyle "${FAST_THEME_NAME}file-extensions-spv" 'fg=136'
_setstyle "${FAST_THEME_NAME}file-extensions-swap" 'fg=95'
_setstyle "${FAST_THEME_NAME}file-extensions-chrt" 'fg=14,bold'
for ext in ass srt ssa sub sup vtt; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=116,bold'; done
for ext in jsm jsp; do _setstyle "${FAST_THEME_NAME}file-extensions-$ext" 'fg=245'; done
_setstyle "${FAST_THEME_NAME}file-extensions-orig" 'fg=241,underline'
_setstyle "${FAST_THEME_NAME}file-extensions-dvi" 'fg=249,bold'
_setstyle "${FAST_THEME_NAME}file-extensions-storyboard" 'fg=196'
_setstyle "${FAST_THEME_NAME}file-extensions-awk" 'fg=103'
_setstyle "${FAST_THEME_NAME}file-extensions-automount" 'fg=66'
_setstyle "${FAST_THEME_NAME}file-extensions-txt" 'fg=248'
_setstyle "${FAST_THEME_NAME}file-extensions-hjson" 'fg=29,bold'
_setstyle "${FAST_THEME_NAME}file-extensions-vimrc" 'fg=56,underline'
# 🥟 pie
